/*
 * Decompiled with CFR 0.152.
 */
package ru.metaculture.protection;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import ru.metaculture.protection.NodePort;
import ru.metaculture.protection.UniformType;
import ru.metaculture.protection.NodeDefinition;

public final class NodeDefinitionRegistry {
    private final Map<String, NodeDefinition> primaryVal = new LinkedHashMap<String, NodeDefinition>();

    public NodeDefinitionRegistry() {
        this.secondaryVal();
    }

    public NodeDefinition primaryVal(String string) {
        return this.primaryVal.get(string);
    }

    public Collection<NodeDefinition> primaryVal() {
        return this.primaryVal.values();
    }

    public List<NodeDefinition> secondaryVal(String string) {
        block6: {
            block5: {
                if (string == null) break block5;
                if (!string.isBlank()) break block6;
            }
            return new ArrayList<NodeDefinition>(this.primaryVal.values());
        }
        String string2 = string.toLowerCase(Locale.ROOT).trim();
        ArrayList<NodeDefinition> arrayList = new ArrayList<NodeDefinition>();
        for (NodeDefinition spanJ : this.primaryVal.values()) {
            if (!spanJ.secondaryVal().toLowerCase(Locale.ROOT).contains(string2)) {
                if (!spanJ.tertiaryVal().toLowerCase(Locale.ROOT).contains(string2) && !spanJ.primaryVal().toLowerCase(Locale.ROOT).contains(string2)) continue;
            }
            arrayList.add(spanJ);
        }
        return arrayList;
    }

    public void primaryVal(NodeDefinition spanJ) {
        this.primaryVal.put(spanJ.primaryVal(), spanJ);
    }

    private void secondaryVal() {
        this.primaryVal(new NodeDefinition("input_uv", "Centered UV", "Inputs", 164.0f, List.of(), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "uv"));
        this.primaryVal(new NodeDefinition("input_global_uv", "Global Screen UV", "Inputs", 180.0f, List.of(), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "globalUv"));
        this.primaryVal(new NodeDefinition("input_screen_uv", "Screen UV", "Inputs", 180.0f, List.of(), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "globalUv"));
        this.primaryVal(new NodeDefinition("input_time", "Time", "Inputs", 164.0f, List.of(), List.of(NodePort.output("time", "time", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "u_Time"));
        this.primaryVal(new NodeDefinition("input_mouse", "Mouse", "Inputs", 164.0f, List.of(), List.of(NodePort.output("mouse", "mouse", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "(u_Mouse / max(u_Resolution, vec2(1.0)))"));
        this.primaryVal(new NodeDefinition("input_global_mouse", "Global Mouse", "Inputs", 178.0f, List.of(), List.of(NodePort.output("mouse", "mouse", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "((u_ElementRect.xy + u_Mouse) / max(u_Resolution, vec2(1.0)))"));
        this.primaryVal(new NodeDefinition("input_element_uv", "Element UV", "Context", 174.0f, List.of(), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "normalizedUv"));
        this.primaryVal(new NodeDefinition("input_element_centered_uv", "Element Centered UV", "Context", 204.0f, List.of(), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "(normalizedUv - 0.5)"));
        this.primaryVal(new NodeDefinition("input_element_rect", "Element Rect", "Context", 184.0f, List.of(), List.of(NodePort.output("rect", "rect", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "u_ElementRect"));
        this.primaryVal(new NodeDefinition("input_element_size", "Element Size", "Context", 184.0f, List.of(), List.of(NodePort.output("size", "size", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "u_ElementRect.zw"));
        this.primaryVal(new NodeDefinition("input_element_radius", "Element Radius", "Context", 190.0f, List.of(), List.of(NodePort.output("radius", "radius", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "u_ElementRadius"));
        this.primaryVal(new NodeDefinition("input_local_mouse", "Local Mouse", "Context", 180.0f, List.of(), List.of(NodePort.output("mouse", "mouse", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "clamp(u_Mouse / max(u_ElementRect.zw, vec2(1.0)), vec2(0.0), vec2(1.0))"));
        this.primaryVal(new NodeDefinition("input_aspect", "Element Aspect", "Context", 186.0f, List.of(), List.of(NodePort.output("aspect", "aspect", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(u_ElementRect.z / max(u_ElementRect.w, 1.0))"));
        this.primaryVal(new NodeDefinition("theme_top", "Accent Top", "Inputs", 174.0f, List.of(), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(u_AccentTop, 1.0)"));
        this.primaryVal(new NodeDefinition("theme_bottom", "Accent Bottom", "Inputs", 174.0f, List.of(), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(u_AccentBottom, 1.0)"));
        this.primaryVal(new NodeDefinition("theme_panel", "Theme Panel", "Inputs", 174.0f, List.of(), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "u_ThemeColors[0]"));
        this.primaryVal(new NodeDefinition("exposed_float", "Exposed Float", "Inputs", 188.0f, List.of(), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.primaryVal(queueVal)));
        this.primaryVal(new NodeDefinition("exposed_color", "Exposed Color", "Inputs", 194.0f, List.of(), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.primaryVal(queueVal)));
        this.primaryVal(new NodeDefinition("float_value", "Float", "Constants", 154.0f, List.of(), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.primaryVal(queueVal.primaryVal("value", 0.5f))));
        this.primaryVal(new NodeDefinition("vec2_value", "Vec2", "Constants", 168.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.5"), NodePort.input("y", "y", UniformType.FLOAT, "0.5")), List.of(NodePort.output("value", "value", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "vec2(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", " + nuuUuvvuVV.primaryVal(queueVal, "y") + ")"));
        this.primaryVal(new NodeDefinition("vec3_value", "Vec3", "Constants", 168.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("y", "y", UniformType.FLOAT, "0.0"), NodePort.input("z", "z", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "vec3(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", " + nuuUuvvuVV.primaryVal(queueVal, "y") + ", " + nuuUuvvuVV.primaryVal(queueVal, "z") + ")"));
        this.primaryVal(new NodeDefinition("vec4_value", "Vec4", "Constants", 174.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "1.0"), NodePort.input("y", "y", UniformType.FLOAT, "1.0"), NodePort.input("z", "z", UniformType.FLOAT, "1.0"), NodePort.input("w", "w", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", " + nuuUuvvuVV.primaryVal(queueVal, "y") + ", " + nuuUuvvuVV.primaryVal(queueVal, "z") + ", " + nuuUuvvuVV.primaryVal(queueVal, "w") + ")"));
        this.primaryVal(new NodeDefinition("base_texture", "Base Texture", "Texture", 190.0f, List.of(), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "texture(u_DiffuseMap, wild_diffuse_uv())"));
        this.primaryVal(new NodeDefinition("input_entity_mask", "Entity Mask", "Entity Context", 188.0f, List.of(), List.of(NodePort.output("mask", "mask", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "step(0.001, texture(u_DiffuseMap, wild_diffuse_uv()).a)"));
        this.primaryVal(new NodeDefinition("input_depth", "Depth", "Entity Context", 164.0f, List.of(), List.of(NodePort.output("depth", "depth", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "clamp(1.0 - texture(u_DiffuseMap, wild_diffuse_uv()).a, 0.0, 1.0)"));
        this.primaryVal(new NodeDefinition("input_camera_distance", "Camera Distance", "Entity Context", 196.0f, List.of(), List.of(NodePort.output("distance", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "length((wild_screen_px() - u_Resolution * 0.5) / max(u_Resolution.y, 1.0))"));
        this.primaryVal(new NodeDefinition("input_camera_dir", "Camera Direction", "World Context", 198.0f, List.of(), List.of(NodePort.output("dir", "dir", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "normalize(vec3(wild_view_dir(vUv), 1.0))"));
        this.primaryVal(new NodeDefinition("input_sun_dir", "Sun Direction", "World Context", 184.0f, List.of(), List.of(NodePort.output("dir", "dir", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "normalize(vec3(cos(u_Time * 0.04), 0.42, sin(u_Time * 0.04)))"));
        this.primaryVal(new NodeDefinition("input_world_time", "World Time", "World Context", 178.0f, List.of(), List.of(NodePort.output("time", "time", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "fract(u_Time * 0.012)"));
        this.primaryVal(new NodeDefinition("input_rain", "Rain Strength", "World Context", 178.0f, List.of(), List.of(NodePort.output("rain", "rain", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "0.0"));
        this.primaryVal(new NodeDefinition("input_biome_tint", "Biome Tint", "World Context", 178.0f, List.of(), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(mix(u_AccentBottom, u_AccentTop, 0.35), 1.0)"));
        this.primaryVal(new NodeDefinition("color_alpha", "Alpha Channel", "Texture", 184.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(1.0)")), List.of(NodePort.output("alpha", "alpha", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").a"));
        this.primaryVal(new NodeDefinition("float_add", "Add Float", "Math", 168.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " + " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("float_mul", "Multiply Float", "Math", 182.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "1.0"), NodePort.input("b", "b", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " * " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("float_sin", "Sine", "Math", 164.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("freq", "freq", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(0.5 + 0.5 * sin((" + nuuUuvvuVV.primaryVal(queueVal, "x") + ") * (" + nuuUuvvuVV.primaryVal(queueVal, "freq") + ")))"));
        this.primaryVal(new NodeDefinition("float_smoothstep", "Smoothstep", "Math", 188.0f, List.of(NodePort.input("edge0", "edge0", UniformType.FLOAT, "0.0"), NodePort.input("edge1", "edge1", UniformType.FLOAT, "1.0"), NodePort.input("x", "x", UniformType.FLOAT, "0.5")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "smoothstep(" + nuuUuvvuVV.primaryVal(queueVal, "edge0") + ", " + nuuUuvvuVV.primaryVal(queueVal, "edge1") + ", " + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("vec4_mix", "Mix Color", "Color", 184.0f, List.of(NodePort.input("a", "a", UniformType.VEC4, "vec4(0.0, 0.0, 0.0, 1.0)"), NodePort.input("b", "b", UniformType.VEC4, "vec4(1.0, 1.0, 1.0, 1.0)"), NodePort.input("t", "t", UniformType.FLOAT, "0.5")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "mix(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", clamp(" + nuuUuvvuVV.primaryVal(queueVal, "t") + ", 0.0, 1.0))"));
        this.primaryVal(new NodeDefinition("sdf_fill", "SDF Fill", "Color", 184.0f, List.of(NodePort.input("mask", "distance", UniformType.FLOAT, "-1.0"), NodePort.input("color", "color", UniformType.VEC4, "u_ThemeColors[0]"), NodePort.input("alpha", "alpha", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4((" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").rgb, (" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").a * wild_sdf_alpha(" + nuuUuvvuVV.primaryVal(queueVal, "mask") + ") * wild_sat(" + nuuUuvvuVV.primaryVal(queueVal, "alpha") + "))"));
        this.primaryVal(new NodeDefinition("element_mask", "Element Mask", "Base Shape", 184.0f, List.of(), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_element_distance()"));
        this.primaryVal(new NodeDefinition("element_alpha", "Element Alpha", "Base Shape", 184.0f, List.of(), List.of(NodePort.output("alpha", "alpha", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_sdf_alpha(wild_element_distance())"));
        this.primaryVal(new NodeDefinition("element_inner_mask", "Inset Element Mask", "Base Shape", 206.0f, List.of(NodePort.input("inset", "inset", UniformType.FLOAT, "1.0")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_element_distance_inset(" + nuuUuvvuVV.primaryVal(queueVal, "inset") + ")"));
        this.primaryVal(new NodeDefinition("glass_surface", "Mica Glass Surface", "Material", 214.0f, List.of(NodePort.input("mask", "mask", UniformType.FLOAT, "wild_element_distance()"), NodePort.input("tint", "tint", UniformType.VEC4, "u_ThemeColors[0]"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "0.58"), NodePort.input("grain", "grain", UniformType.FLOAT, "0.045")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_glass_surface(" + nuuUuvvuVV.primaryVal(queueVal, "mask") + ", " + nuuUuvvuVV.primaryVal(queueVal, "tint") + ", " + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ", " + nuuUuvvuVV.primaryVal(queueVal, "grain") + ")"));
        this.primaryVal(new NodeDefinition("rim_light", "Rim Light", "Material", 196.0f, List.of(NodePort.input("mask", "mask", UniformType.FLOAT, "wild_element_distance()"), NodePort.input("color", "color", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("thickness", "width", UniformType.FLOAT, "1.0"), NodePort.input("intensity", "power", UniformType.FLOAT, "0.18")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_rim_light(" + nuuUuvvuVV.primaryVal(queueVal, "mask") + ", " + nuuUuvvuVV.primaryVal(queueVal, "color") + ", " + nuuUuvvuVV.primaryVal(queueVal, "thickness") + ", " + nuuUuvvuVV.primaryVal(queueVal, "intensity") + ")"));
        this.primaryVal(new NodeDefinition("hover_glow", "Magnetic Hover Glow", "Material", 220.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "normalizedUv"), NodePort.input("color", "color", UniformType.VEC4, "vec4(u_AccentBottom, 1.0)"), NodePort.input("radius", "radius", UniformType.FLOAT, "0.42"), NodePort.input("intensity", "power", UniformType.FLOAT, "0.58")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_hover_glow(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "color") + ", " + nuuUuvvuVV.primaryVal(queueVal, "radius") + ", " + nuuUuvvuVV.primaryVal(queueVal, "intensity") + ")"));
        this.primaryVal(new NodeDefinition("inner_shadow", "Inner Shadow", "Material", 198.0f, List.of(NodePort.input("mask", "mask", UniformType.FLOAT, "wild_element_distance()"), NodePort.input("strength", "power", UniformType.FLOAT, "0.22"), NodePort.input("width", "width", UniformType.FLOAT, "12.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_inner_shadow(" + nuuUuvvuVV.primaryVal(queueVal, "mask") + ", " + nuuUuvvuVV.primaryVal(queueVal, "strength") + ", " + nuuUuvvuVV.primaryVal(queueVal, "width") + ")"));
        this.primaryVal(new NodeDefinition("exposure_lift", "Photographic Exposure", "Material", 226.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "u_ThemeColors[0]"), NodePort.input("amount", "amount", UniformType.FLOAT, "0.18"), NodePort.input("decay", "decay", UniformType.FLOAT, "2.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_exposure_lift(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ", " + nuuUuvvuVV.primaryVal(queueVal, "amount") + ", " + nuuUuvvuVV.primaryVal(queueVal, "decay") + ")"));
        this.primaryVal(new NodeDefinition("alpha_blend", "Alpha Blend", "Blend", 190.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.0)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(1.0)")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_alpha_over(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ", " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ")"));
        this.primaryVal(new NodeDefinition("color_ramp", "Color Ramp", "Color", 184.0f, List.of(NodePort.input("t", "t", UniformType.FLOAT, "0.5"), NodePort.input("a", "a", UniformType.VEC4, "vec4(u_AccentBottom, 1.0)"), NodePort.input("b", "b", UniformType.VEC4, "vec4(u_AccentTop, 1.0)")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "mix(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", wild_sat(" + nuuUuvvuVV.primaryVal(queueVal, "t") + "))"));
        this.primaryVal(new NodeDefinition("color_multiply_scalar", "Color Multiply", "Color", 198.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(1.0)"), NodePort.input("factor", "factor", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4((" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").rgb * " + nuuUuvvuVV.primaryVal(queueVal, "factor") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").a)"));
        this.primaryVal(new NodeDefinition("blend_screen", "Screen Blend", "Blend", 188.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.02, 0.022, 0.028, 1.0)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "0.5")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_blend_screen(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ", " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ", " + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ")"));
        this.primaryVal(new NodeDefinition("blend_overlay", "Overlay Blend", "Blend", 188.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.02, 0.022, 0.028, 1.0)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentBottom, 1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "0.5")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_blend_overlay(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ", " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ", " + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ")"));
        this.primaryVal(new NodeDefinition("sdf_circle", "SDF Circle", "SDF", 184.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.0)"), NodePort.input("radius", "radius", UniformType.FLOAT, "0.25"), NodePort.input("softness", "soft", UniformType.FLOAT, "0.08")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_circle(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "center") + ") * (u_ElementRect.zw * 0.5), (" + nuuUuvvuVV.primaryVal(queueVal, "radius") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5, " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")" : "wild_sdf_circle(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "radius") + ", " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")"));
        this.primaryVal(new NodeDefinition("sdf_round_box", "SDF Rounded Box", "SDF", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.0)"), NodePort.input("size", "size", UniformType.VEC2, "vec2(0.95, 0.32)"), NodePort.input("radius", "radius", UniformType.FLOAT, "0.08"), NodePort.input("softness", "soft", UniformType.FLOAT, "0.06")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_round_box(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "center") + ") * (u_ElementRect.zw * 0.5), (" + nuuUuvvuVV.primaryVal(queueVal, "size") + ") * (u_ElementRect.zw * 0.5), (" + nuuUuvvuVV.primaryVal(queueVal, "radius") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5, " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")" : "wild_sdf_round_box(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "size") + ", " + nuuUuvvuVV.primaryVal(queueVal, "radius") + ", " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")"));
        this.primaryVal(new NodeDefinition("simplex_noise_3d", "Simplex Noise 3D", "Generator", 202.0f, List.of(NodePort.input("p", "p", UniformType.VEC3, "vec3(globalUv * 2.0, u_Time * 0.08)"), NodePort.input("scale", "scale", UniformType.FLOAT, "3.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(0.5 + 0.5 * wild_simplex3(" + nuuUuvvuVV.primaryVal(queueVal, "p") + " * " + nuuUuvvuVV.primaryVal(queueVal, "scale") + "))"));
        this.primaryVal(new NodeDefinition("voronoi", "Voronoi", "Generator", 190.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "globalUv"), NodePort.input("scale", "scale", UniformType.FLOAT, "7.0"), NodePort.input("time", "time", UniformType.FLOAT, "u_Time")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_voronoi(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + " * " + nuuUuvvuVV.primaryVal(queueVal, "scale") + ", " + nuuUuvvuVV.primaryVal(queueVal, "time") + ")"));
        this.primaryVal(new NodeDefinition("chromatic_aberration", "Chromatic Aberration", "VFX", 218.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("amount", "amount", UniformType.FLOAT, "0.08"), NodePort.input("phase", "phase", UniformType.FLOAT, "u_Time")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_chromatic(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ", vUv, " + nuuUuvvuVV.primaryVal(queueVal, "amount") + ", " + nuuUuvvuVV.primaryVal(queueVal, "phase") + ")"));
        this.primaryVal(new NodeDefinition("output_color", "Master Output", "Output", 184.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.02, 0.022, 0.028, 1.0)"), NodePort.input("alpha", "alpha", UniformType.FLOAT, "1.0")), List.of(), (nuuUuvvuVV, queueVal, string) -> "vec4((" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").rgb, (" + nuuUuvvuVV.primaryVal(queueVal, "color") + ").a * " + nuuUuvvuVV.primaryVal(queueVal, "alpha") + ")"));
        this.primaryVal(new NodeDefinition("sdf_triangle", "SDF Triangle", "SDF", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.0)"), NodePort.input("radius", "radius", UniformType.FLOAT, "0.35"), NodePort.input("softness", "soft", UniformType.FLOAT, "0.05")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_triangle(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "center") + ") * (u_ElementRect.zw * 0.5), (" + nuuUuvvuVV.primaryVal(queueVal, "radius") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5, " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")" : "wild_sdf_triangle(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "radius") + ", " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")"));
        this.primaryVal(new NodeDefinition("sdf_hex", "SDF Hexagon", "SDF", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.0)"), NodePort.input("radius", "radius", UniformType.FLOAT, "0.28"), NodePort.input("softness", "soft", UniformType.FLOAT, "0.05")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_hex(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "center") + ") * (u_ElementRect.zw * 0.5), (" + nuuUuvvuVV.primaryVal(queueVal, "radius") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5, " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")" : "wild_sdf_hex(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "radius") + ", " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")"));
        this.primaryVal(new NodeDefinition("fbm_noise", "FBM Noise", "Generator", 196.0f, List.of(NodePort.input("p", "p", UniformType.VEC3, "vec3(globalUv * 3.0, u_Time * 0.12)"), NodePort.input("octaves", "oct", UniformType.FLOAT, "5.0"), NodePort.input("scale", "scale", UniformType.FLOAT, "1.8")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_fbm(" + nuuUuvvuVV.primaryVal(queueVal, "p") + " * " + nuuUuvvuVV.primaryVal(queueVal, "scale") + ", int(clamp(" + nuuUuvvuVV.primaryVal(queueVal, "octaves") + ", 1.0, 8.0)))"));
        this.primaryVal(new NodeDefinition("polar_uv", "Polar UV", "Coords", 184.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.5)")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "wild_polar(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ")"));
        this.primaryVal(new NodeDefinition("rotate_uv", "Rotate UV", "Coords", 186.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.5)"), NodePort.input("angle", "angle", UniformType.FLOAT, "u_Time")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "wild_rotate_uv(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "angle") + ")"));
        this.primaryVal(new NodeDefinition("twist_uv", "Twist UV", "Coords", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.5)"), NodePort.input("strength", "strength", UniformType.FLOAT, "2.6")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "wild_twist_uv(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "strength") + ")"));
        this.primaryVal(new NodeDefinition("vignette", "Vignette", "VFX", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("intensity", "intensity", UniformType.FLOAT, "1.0"), NodePort.input("falloff", "falloff", UniformType.FLOAT, "0.5")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_vignette(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "intensity") + ", " + nuuUuvvuVV.primaryVal(queueVal, "falloff") + ")"));
        this.primaryVal(new NodeDefinition("posterize", "Posterize", "VFX", 196.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("steps", "steps", UniformType.FLOAT, "6.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(floor(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb * max(" + nuuUuvvuVV.primaryVal(queueVal, "steps") + ", 1.0)) / max(" + nuuUuvvuVV.primaryVal(queueVal, "steps") + ", 1.0), " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("bloom_lift", "Bloom Lift", "VFX", 196.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("threshold", "threshold", UniformType.FLOAT, "0.6"), NodePort.input("amount", "amount", UniformType.FLOAT, "1.2")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_bloom_lift(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ", " + nuuUuvvuVV.primaryVal(queueVal, "threshold") + ", " + nuuUuvvuVV.primaryVal(queueVal, "amount") + ")"));
        this.primaryVal(new NodeDefinition("color_pulse", "Color Pulse", "Color", 196.0f, List.of(NodePort.input("a", "a", UniformType.VEC4, "vec4(u_AccentBottom, 1.0)"), NodePort.input("b", "b", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("speed", "speed", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "mix(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", 0.5 + 0.5 * sin(u_Time * " + nuuUuvvuVV.primaryVal(queueVal, "speed") + "))"));
        this.primaryVal(new NodeDefinition("color_screen_split", "Channel Split", "Color", 196.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("amount", "amount", UniformType.FLOAT, "0.04")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_channel_split(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ", " + nuuUuvvuVV.primaryVal(queueVal, "amount") + ", u_Time)"));
        this.primaryVal(new NodeDefinition("fresnel", "Fresnel Rim", "VFX", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("power", "power", UniformType.FLOAT, "3.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "pow(max(1.0 - 2.0 * length(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + " - 0.5), 0.0), max(" + nuuUuvvuVV.primaryVal(queueVal, "power") + ", 0.001))"));
        this.primaryVal(new NodeDefinition("step_threshold", "Step Threshold", "Math", 184.0f, List.of(NodePort.input("edge", "edge", UniformType.FLOAT, "0.5"), NodePort.input("x", "x", UniformType.FLOAT, "0.5")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "step(" + nuuUuvvuVV.primaryVal(queueVal, "edge") + ", " + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("fract_node", "Fract", "Math", 174.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "fract(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("abs_node", "Abs", "Math", 168.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "abs(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("saturate_node", "Saturate", "Math", 174.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "clamp(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", 0.0, 1.0)"));
        this.primaryVal(new NodeDefinition("blend_multiply", "Multiply Blend", "Blend", 196.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.02, 0.022, 0.028, 1.0)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "0.5")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(mix(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb, " + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb * " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".rgb, clamp(" + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ", 0.0, 1.0)), max(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".a, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".a))"));
        this.primaryVal(new NodeDefinition("blend_add", "Additive Blend", "Blend", 196.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.02, 0.022, 0.028, 1.0)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "0.5")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(clamp(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb + " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".rgb * clamp(" + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ", 0.0, 1.0), 0.0, 1.0), max(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".a, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".a))"));
        this.primaryVal(new NodeDefinition("iridescence", "Iridescence", "Color", 200.0f, List.of(NodePort.input("t", "t", UniformType.FLOAT, "0.5"), NodePort.input("speed", "speed", UniformType.FLOAT, "0.8")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_iridescence(" + nuuUuvvuVV.primaryVal(queueVal, "t") + ", " + nuuUuvvuVV.primaryVal(queueVal, "speed") + ")"));
        this.primaryVal(new NodeDefinition("sdf_union", "SDF Union", "SDF Booleans", 196.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0"), NodePort.input("smoothness", "smooth", UniformType.FLOAT, "0.05")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_union(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "smoothness") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5)" : "wild_sdf_union(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", " + nuuUuvvuVV.primaryVal(queueVal, "smoothness") + ")"));
        this.primaryVal(new NodeDefinition("sdf_subtract", "SDF Subtract", "SDF Booleans", 200.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0"), NodePort.input("smoothness", "smooth", UniformType.FLOAT, "0.05")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_subtract(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "smoothness") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5)" : "wild_sdf_subtract(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", " + nuuUuvvuVV.primaryVal(queueVal, "smoothness") + ")"));
        this.primaryVal(new NodeDefinition("sdf_intersect", "SDF Intersect", "SDF Booleans", 204.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0"), NodePort.input("smoothness", "smooth", UniformType.FLOAT, "0.05")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_intersect(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "smoothness") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5)" : "wild_sdf_intersect(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", " + nuuUuvvuVV.primaryVal(queueVal, "smoothness") + ")"));
        this.primaryVal(new NodeDefinition("sdf_star", "SDF Star", "SDF", 198.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.0)"), NodePort.input("radius", "radius", UniformType.FLOAT, "0.32"), NodePort.input("points", "points", UniformType.FLOAT, "5.0"), NodePort.input("softness", "soft", UniformType.FLOAT, "0.05")), List.of(NodePort.output("mask", "distance", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> nuuUuvvuVV.secondaryVal() ? "wild_sdf_star(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", (" + nuuUuvvuVV.primaryVal(queueVal, "center") + ") * (u_ElementRect.zw * 0.5), (" + nuuUuvvuVV.primaryVal(queueVal, "radius") + ") * min(u_ElementRect.z, u_ElementRect.w) * 0.5, " + nuuUuvvuVV.primaryVal(queueVal, "points") + ", " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")" : "wild_sdf_star(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "radius") + ", " + nuuUuvvuVV.primaryVal(queueVal, "points") + ", " + nuuUuvvuVV.primaryVal(queueVal, "softness") + ")"));
        this.primaryVal(new NodeDefinition("math_remap", "Remap", "Math", 196.0f, List.of(NodePort.input("v", "v", UniformType.FLOAT, "0.5"), NodePort.input("inMin", "inMin", UniformType.FLOAT, "0.0"), NodePort.input("inMax", "inMax", UniformType.FLOAT, "1.0"), NodePort.input("outMin", "outMin", UniformType.FLOAT, "0.0"), NodePort.input("outMax", "outMax", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_remap(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ", " + nuuUuvvuVV.primaryVal(queueVal, "inMin") + ", " + nuuUuvvuVV.primaryVal(queueVal, "inMax") + ", " + nuuUuvvuVV.primaryVal(queueVal, "outMin") + ", " + nuuUuvvuVV.primaryVal(queueVal, "outMax") + ")"));
        this.primaryVal(new NodeDefinition("math_clamp", "Clamp", "Math", 184.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.5"), NodePort.input("min", "min", UniformType.FLOAT, "0.0"), NodePort.input("max", "max", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "clamp(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", " + nuuUuvvuVV.primaryVal(queueVal, "min") + ", " + nuuUuvvuVV.primaryVal(queueVal, "max") + ")"));
        this.primaryVal(new NodeDefinition("math_floor", "Floor", "Math", 168.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "floor(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("math_ceil", "Ceil", "Math", 168.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "ceil(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("math_length", "Length", "Math", 184.0f, List.of(NodePort.input("v", "v", UniformType.VEC2, "vUv - 0.5")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "length(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ")"));
        this.primaryVal(new NodeDefinition("math_distance", "Distance", "Math", 192.0f, List.of(NodePort.input("a", "a", UniformType.VEC2, "vUv"), NodePort.input("b", "b", UniformType.VEC2, "vec2(0.5)")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "distance(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("math_power", "Power", "Math", 192.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.5"), NodePort.input("y", "y", UniformType.FLOAT, "2.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "pow(max(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", 0.0), " + nuuUuvvuVV.primaryVal(queueVal, "y") + ")"));
        this.primaryVal(new NodeDefinition("math_mod", "Mod", "Math", 188.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("y", "y", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "mod(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", (abs(" + nuuUuvvuVV.primaryVal(queueVal, "y") + ") < 1e-5 ? 1e-5 : " + nuuUuvvuVV.primaryVal(queueVal, "y") + "))"));
        this.primaryVal(new NodeDefinition("math_dot", "Dot", "Math", 188.0f, List.of(NodePort.input("a", "a", UniformType.VEC2, "vUv"), NodePort.input("b", "b", UniformType.VEC2, "vec2(1.0)")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "dot(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("math_subtract", "Subtract", "Math", 184.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " - " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("math_divide", "Divide", "Math", 184.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "1.0"), NodePort.input("b", "b", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " / max(" + nuuUuvvuVV.primaryVal(queueVal, "b") + ", 1e-5))"));
        this.primaryVal(new NodeDefinition("color_gradient_map", "Gradient Map", "Color", 220.0f, List.of(NodePort.input("t", "t", UniformType.FLOAT, "0.5"), NodePort.input("a", "a", UniformType.VEC4, "vec4(u_AccentBottom, 1.0)"), NodePort.input("b", "b", UniformType.VEC4, "vec4(u_AccentTop, 1.0)"), NodePort.input("c", "c", UniformType.VEC4, "vec4(1.0)")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "wild_gradient_map(" + nuuUuvvuVV.primaryVal(queueVal, "t") + ", " + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", " + nuuUuvvuVV.primaryVal(queueVal, "c") + ")"));
        this.primaryVal(new NodeDefinition("color_desaturate", "Desaturate", "Color", 192.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(1.0)"), NodePort.input("amount", "amount", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(wild_desaturate(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb, " + nuuUuvvuVV.primaryVal(queueVal, "amount") + "), " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("color_invert", "Invert", "Color", 188.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("amount", "amount", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(wild_invert(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb, " + nuuUuvvuVV.primaryVal(queueVal, "amount") + "), " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("color_hsv", "HSV \u2192 RGB", "Color", 196.0f, List.of(NodePort.input("h", "hue", UniformType.FLOAT, "0.0"), NodePort.input("s", "sat", UniformType.FLOAT, "1.0"), NodePort.input("v", "val", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(wild_hsv2rgb(vec3(" + nuuUuvvuVV.primaryVal(queueVal, "h") + ", " + nuuUuvvuVV.primaryVal(queueVal, "s") + ", " + nuuUuvvuVV.primaryVal(queueVal, "v") + ")), 1.0)"));
        this.primaryVal(new NodeDefinition("time_bpm", "BPM Sync", "Time", 192.0f, List.of(NodePort.input("bpm", "bpm", UniformType.FLOAT, "128.0"), NodePort.input("strength", "shape", UniformType.FLOAT, "2.0")), List.of(NodePort.output("pulse", "pulse", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_bpm(" + nuuUuvvuVV.primaryVal(queueVal, "bpm") + ", " + nuuUuvvuVV.primaryVal(queueVal, "strength") + ")"));
        this.primaryVal(new NodeDefinition("time_pulse", "Pulse", "Time", 184.0f, List.of(NodePort.input("t", "t", UniformType.FLOAT, "u_Time"), NodePort.input("duty", "duty", UniformType.FLOAT, "0.5")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_pulse(" + nuuUuvvuVV.primaryVal(queueVal, "t") + ", " + nuuUuvvuVV.primaryVal(queueVal, "duty") + ")"));
        this.primaryVal(new NodeDefinition("input_view_dir", "View Direction", "Inputs", 178.0f, List.of(), List.of(NodePort.output("dir", "dir", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "wild_view_dir(vUv)"));
        this.primaryVal(new NodeDefinition("input_normal", "Normal (UV slope)", "Inputs", 192.0f, List.of(NodePort.input("strength", "strength", UniformType.FLOAT, "4.0")), List.of(NodePort.output("normal", "normal", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "wild_normal_from_uv(vUv, " + nuuUuvvuVV.primaryVal(queueVal, "strength") + ")"));
        this.primaryVal(new NodeDefinition("input_resolution", "Resolution", "Inputs", 178.0f, List.of(), List.of(NodePort.output("res", "res", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "u_Resolution"));
        this.primaryVal(new NodeDefinition("input_alpha", "Alpha", "Inputs", 178.0f, List.of(), List.of(NodePort.output("alpha", "alpha", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "u_Alpha"));
        this.primaryVal(new NodeDefinition("vec2_split", "Split Vec2", "Math", 188.0f, List.of(NodePort.input("v", "v", UniformType.VEC2, "vUv")), List.of(NodePort.output("x", "x", UniformType.FLOAT), NodePort.output("y", "y", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "x".equals(string) ? "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").x" : "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").y"));
        this.primaryVal(new NodeDefinition("math_max", "Max", "Math", 184.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "max(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("math_min", "Min", "Math", 184.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.0"), NodePort.input("b", "b", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "min(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("math_sign", "Sign", "Math", 172.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "sign(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("math_sqrt", "Square Root", "Math", 178.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "sqrt(max(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", 0.0))"));
        this.primaryVal(new NodeDefinition("math_exp", "Exp", "Math", 172.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "exp(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("math_log", "Log", "Math", 172.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "log(max(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", 1e-6))"));
        this.primaryVal(new NodeDefinition("math_one_minus", "One Minus", "Math", 178.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(1.0 - " + nuuUuvvuVV.primaryVal(queueVal, "x") + ")"));
        this.primaryVal(new NodeDefinition("math_reciprocal", "Reciprocal", "Math", 184.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(1.0 / (abs(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ") < 1e-5 ? 1e-5 : " + nuuUuvvuVV.primaryVal(queueVal, "x") + "))"));
        this.primaryVal(new NodeDefinition("math_round", "Round", "Math", 172.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "floor(" + nuuUuvvuVV.primaryVal(queueVal, "x") + " + 0.5)"));
        this.primaryVal(new NodeDefinition("math_cos", "Cosine", "Math", 172.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("freq", "freq", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "cos((" + nuuUuvvuVV.primaryVal(queueVal, "x") + ") * (" + nuuUuvvuVV.primaryVal(queueVal, "freq") + "))"));
        this.primaryVal(new NodeDefinition("math_sin_raw", "Sine Raw", "Math", 178.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("freq", "freq", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "sin((" + nuuUuvvuVV.primaryVal(queueVal, "x") + ") * (" + nuuUuvvuVV.primaryVal(queueVal, "freq") + "))"));
        this.primaryVal(new NodeDefinition("math_atan2", "Atan2", "Math", 178.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "1.0"), NodePort.input("b", "b", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "atan(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec_add3", "Add Vec3", "Vector", 178.0f, List.of(NodePort.input("a", "a", UniformType.VEC3, "vec3(0.0)"), NodePort.input("b", "b", UniformType.VEC3, "vec3(0.0)")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " + " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec_sub3", "Subtract Vec3", "Vector", 190.0f, List.of(NodePort.input("a", "a", UniformType.VEC3, "vec3(0.0)"), NodePort.input("b", "b", UniformType.VEC3, "vec3(0.0)")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " - " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec_mul3", "Multiply Vec3", "Vector", 190.0f, List.of(NodePort.input("a", "a", UniformType.VEC3, "vec3(1.0)"), NodePort.input("b", "b", UniformType.VEC3, "vec3(1.0)")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " * " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec_scale3", "Scale Vec3", "Vector", 184.0f, List.of(NodePort.input("v", "v", UniformType.VEC3, "vec3(1.0)"), NodePort.input("s", "s", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + " * " + nuuUuvvuVV.primaryVal(queueVal, "s") + ")"));
        this.primaryVal(new NodeDefinition("vec_normalize", "Normalize", "Vector", 184.0f, List.of(NodePort.input("v", "v", UniformType.VEC3, "vec3(0.0,0.0,1.0)")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "normalize(" + nuuUuvvuVV.primaryVal(queueVal, "v") + " + 1e-6)"));
        this.primaryVal(new NodeDefinition("vec_cross", "Cross", "Vector", 178.0f, List.of(NodePort.input("a", "a", UniformType.VEC3, "vec3(0.0)"), NodePort.input("b", "b", UniformType.VEC3, "vec3(0.0)")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "cross(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec_reflect", "Reflect", "Vector", 184.0f, List.of(NodePort.input("i", "i", UniformType.VEC3, "vec3(0.0,0.0,-1.0)"), NodePort.input("n", "n", UniformType.VEC3, "vec3(0.0,0.0,1.0)")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "reflect(" + nuuUuvvuVV.primaryVal(queueVal, "i") + ", normalize(" + nuuUuvvuVV.primaryVal(queueVal, "n") + "))"));
        this.primaryVal(new NodeDefinition("vec_dot3", "Dot Vec3", "Vector", 178.0f, List.of(NodePort.input("a", "a", UniformType.VEC3, "vec3(0.0)"), NodePort.input("b", "b", UniformType.VEC3, "vec3(0.0)")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "dot(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec_lerp3", "Lerp Vec3", "Vector", 184.0f, List.of(NodePort.input("a", "a", UniformType.VEC3, "vec3(0.0)"), NodePort.input("b", "b", UniformType.VEC3, "vec3(0.0)"), NodePort.input("t", "t", UniformType.FLOAT, "0.5")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "mix(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", " + nuuUuvvuVV.primaryVal(queueVal, "t") + ")"));
        this.primaryVal(new NodeDefinition("vec2_add", "Add Vec2", "Vector", 178.0f, List.of(NodePort.input("a", "a", UniformType.VEC2, "vec2(0.0)"), NodePort.input("b", "b", UniformType.VEC2, "vec2(0.0)")), List.of(NodePort.output("value", "value", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " + " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec2_mul", "Multiply Vec2", "Vector", 190.0f, List.of(NodePort.input("a", "a", UniformType.VEC2, "vec2(1.0)"), NodePort.input("b", "b", UniformType.VEC2, "vec2(1.0)")), List.of(NodePort.output("value", "value", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " * " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec4_add", "Add Vec4", "Vector", 178.0f, List.of(NodePort.input("a", "a", UniformType.VEC4, "vec4(0.0)"), NodePort.input("b", "b", UniformType.VEC4, "vec4(0.0)")), List.of(NodePort.output("value", "value", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "a") + " + " + nuuUuvvuVV.primaryVal(queueVal, "b") + ")"));
        this.primaryVal(new NodeDefinition("vec4_scale", "Scale Vec4", "Vector", 184.0f, List.of(NodePort.input("v", "v", UniformType.VEC4, "vec4(1.0)"), NodePort.input("s", "s", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + " * " + nuuUuvvuVV.primaryVal(queueVal, "s") + ")"));
        this.primaryVal(new NodeDefinition("combine_vec3", "Combine Vec3", "Vector", 184.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("y", "y", UniformType.FLOAT, "0.0"), NodePort.input("z", "z", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.VEC3)), (nuuUuvvuVV, queueVal, string) -> "vec3(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", " + nuuUuvvuVV.primaryVal(queueVal, "y") + ", " + nuuUuvvuVV.primaryVal(queueVal, "z") + ")"));
        this.primaryVal(new NodeDefinition("combine_vec4", "Combine Vec4", "Vector", 190.0f, List.of(NodePort.input("x", "x", UniformType.FLOAT, "0.0"), NodePort.input("y", "y", UniformType.FLOAT, "0.0"), NodePort.input("z", "z", UniformType.FLOAT, "0.0"), NodePort.input("w", "w", UniformType.FLOAT, "1.0")), List.of(NodePort.output("value", "value", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(" + nuuUuvvuVV.primaryVal(queueVal, "x") + ", " + nuuUuvvuVV.primaryVal(queueVal, "y") + ", " + nuuUuvvuVV.primaryVal(queueVal, "z") + ", " + nuuUuvvuVV.primaryVal(queueVal, "w") + ")"));
        this.primaryVal(new NodeDefinition("split_vec3", "Split Vec3", "Vector", 184.0f, List.of(NodePort.input("v", "v", UniformType.VEC3, "vec3(0.0)")), List.of(NodePort.output("x", "x", UniformType.FLOAT), NodePort.output("y", "y", UniformType.FLOAT), NodePort.output("z", "z", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "x".equals(string) ? "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").x" : ("y".equals(string) ? "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").y" : "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").z")));
        this.primaryVal(new NodeDefinition("split_vec4", "Split Vec4", "Vector", 190.0f, List.of(NodePort.input("v", "v", UniformType.VEC4, "vec4(0.0)")), List.of(NodePort.output("x", "x", UniformType.FLOAT), NodePort.output("y", "y", UniformType.FLOAT), NodePort.output("z", "z", UniformType.FLOAT), NodePort.output("w", "w", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "x".equals(string) ? "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").x" : ("y".equals(string) ? "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").y" : ("z".equals(string) ? "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").z" : "(" + nuuUuvvuVV.primaryVal(queueVal, "v") + ").w"))));
        this.primaryVal(new NodeDefinition("uv_tiling_offset", "Tiling And Offset", "Coords", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("tiling", "tiling", UniformType.VEC2, "vec2(1.0)"), NodePort.input("offset", "offset", UniformType.VEC2, "vec2(0.0)")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + " * " + nuuUuvvuVV.primaryVal(queueVal, "tiling") + " + " + nuuUuvvuVV.primaryVal(queueVal, "offset") + ")"));
        this.primaryVal(new NodeDefinition("uv_panner", "Panner", "Coords", 186.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "uv"), NodePort.input("speed", "speed", UniformType.VEC2, "vec2(0.1)"), NodePort.input("time", "time", UniformType.FLOAT, "u_Time")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + " + " + nuuUuvvuVV.primaryVal(queueVal, "speed") + " * " + nuuUuvvuVV.primaryVal(queueVal, "time") + ")"));
        this.primaryVal(new NodeDefinition("uv_radial_shear", "Radial Shear", "Coords", 196.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.5)"), NodePort.input("strength", "strength", UniformType.FLOAT, "6.0")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "wild_radial_shear(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "strength") + ")"));
        this.primaryVal(new NodeDefinition("uv_spherize", "Spherize", "Coords", 190.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("center", "center", UniformType.VEC2, "vec2(0.5)"), NodePort.input("strength", "strength", UniformType.FLOAT, "0.5")), List.of(NodePort.output("uv", "uv", UniformType.VEC2)), (nuuUuvvuVV, queueVal, string) -> "wild_spherize(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "center") + ", " + nuuUuvvuVV.primaryVal(queueVal, "strength") + ")"));
        this.primaryVal(new NodeDefinition("checkerboard", "Checkerboard", "Generator", 200.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "vUv"), NodePort.input("freq", "freq", UniformType.VEC2, "vec2(6.0)"), NodePort.input("a", "a", UniformType.VEC4, "vec4(0.05,0.05,0.06,1.0)"), NodePort.input("b", "b", UniformType.VEC4, "vec4(u_AccentTop,1.0)")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "mix(" + nuuUuvvuVV.primaryVal(queueVal, "a") + ", " + nuuUuvvuVV.primaryVal(queueVal, "b") + ", wild_checker(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + ", " + nuuUuvvuVV.primaryVal(queueVal, "freq") + "))"));
        this.primaryVal(new NodeDefinition("simple_noise", "Simple Noise", "Generator", 190.0f, List.of(NodePort.input("uv", "uv", UniformType.VEC2, "globalUv"), NodePort.input("scale", "scale", UniformType.FLOAT, "5.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "wild_gnoise2(" + nuuUuvvuVV.primaryVal(queueVal, "uv") + " * " + nuuUuvvuVV.primaryVal(queueVal, "scale") + ")"));
        this.primaryVal(new NodeDefinition("contrast", "Contrast", "Color", 190.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("amount", "amount", UniformType.FLOAT, "1.2")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4((" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb - 0.5) * " + nuuUuvvuVV.primaryVal(queueVal, "amount") + " + 0.5, " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("saturation", "Saturation", "Color", 190.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("amount", "amount", UniformType.FLOAT, "1.2")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(mix(vec3(dot(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb, vec3(0.299,0.587,0.114))), " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb, " + nuuUuvvuVV.primaryVal(queueVal, "amount") + "), " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("brightness", "Brightness", "Color", 190.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(0.5)"), NodePort.input("amount", "amount", UniformType.FLOAT, "0.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb + " + nuuUuvvuVV.primaryVal(queueVal, "amount") + ", " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("hue_shift", "Hue Shift", "Color", 190.0f, List.of(NodePort.input("color", "color", UniformType.VEC4, "vec4(u_AccentTop,1.0)"), NodePort.input("shift", "shift", UniformType.FLOAT, "0.1")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(wild_hsv2rgb(vec3(fract(wild_rgb2hsv(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb).x + " + nuuUuvvuVV.primaryVal(queueVal, "shift") + "), wild_rgb2hsv(" + nuuUuvvuVV.primaryVal(queueVal, "color") + ".rgb).yz)), " + nuuUuvvuVV.primaryVal(queueVal, "color") + ".a)"));
        this.primaryVal(new NodeDefinition("blend_lighten", "Lighten Blend", "Blend", 196.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.1)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentTop,1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(mix(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb, max(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".rgb), clamp(" + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ",0.0,1.0)), max(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".a, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".a))"));
        this.primaryVal(new NodeDefinition("blend_darken", "Darken Blend", "Blend", 196.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.1)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentTop,1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(mix(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb, min(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".rgb), clamp(" + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ",0.0,1.0)), max(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".a, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".a))"));
        this.primaryVal(new NodeDefinition("blend_difference", "Difference Blend", "Blend", 200.0f, List.of(NodePort.input("base", "base", UniformType.VEC4, "vec4(0.1)"), NodePort.input("layer", "layer", UniformType.VEC4, "vec4(u_AccentTop,1.0)"), NodePort.input("opacity", "opacity", UniformType.FLOAT, "1.0")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "vec4(mix(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb, abs(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".rgb - " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".rgb), clamp(" + nuuUuvvuVV.primaryVal(queueVal, "opacity") + ",0.0,1.0)), max(" + nuuUuvvuVV.primaryVal(queueVal, "base") + ".a, " + nuuUuvvuVV.primaryVal(queueVal, "layer") + ".a))"));
        this.primaryVal(new NodeDefinition("branch", "Branch", "Logic", 190.0f, List.of(NodePort.input("pred", "pred", UniformType.FLOAT, "0.0"), NodePort.input("whenTrue", "true", UniformType.VEC4, "vec4(u_AccentTop,1.0)"), NodePort.input("whenFalse", "false", UniformType.VEC4, "vec4(u_AccentBottom,1.0)")), List.of(NodePort.output("color", "color", UniformType.VEC4)), (nuuUuvvuVV, queueVal, string) -> "mix(" + nuuUuvvuVV.primaryVal(queueVal, "whenFalse") + ", " + nuuUuvvuVV.primaryVal(queueVal, "whenTrue") + ", step(0.5, " + nuuUuvvuVV.primaryVal(queueVal, "pred") + "))"));
        this.primaryVal(new NodeDefinition("compare_greater", "Greater Than", "Logic", 196.0f, List.of(NodePort.input("a", "a", UniformType.FLOAT, "0.5"), NodePort.input("b", "b", UniformType.FLOAT, "0.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "step(" + nuuUuvvuVV.primaryVal(queueVal, "b") + ", " + nuuUuvvuVV.primaryVal(queueVal, "a") + ")"));
        this.primaryVal(new NodeDefinition("time_sine", "Time Sine", "Time", 178.0f, List.of(), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(0.5 + 0.5 * sin(u_Time))"));
        this.primaryVal(new NodeDefinition("time_cosine", "Time Cosine", "Time", 184.0f, List.of(), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "(0.5 + 0.5 * cos(u_Time))"));
        this.primaryVal(new NodeDefinition("time_raw", "Time Raw", "Time", 172.0f, List.of(), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "u_Time"));
        this.primaryVal(new NodeDefinition("fresnel_real", "Fresnel Effect", "VFX", 200.0f, List.of(NodePort.input("normal", "normal", UniformType.VEC3, "vec3(0.0,0.0,1.0)"), NodePort.input("viewDir", "view", UniformType.VEC3, "vec3(0.0,0.0,1.0)"), NodePort.input("power", "power", UniformType.FLOAT, "3.0")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "pow(1.0 - clamp(dot(normalize(" + nuuUuvvuVV.primaryVal(queueVal, "normal") + "), normalize(" + nuuUuvvuVV.primaryVal(queueVal, "viewDir") + ")), 0.0, 1.0), max(" + nuuUuvvuVV.primaryVal(queueVal, "power") + ", 0.001))"));
        this.primaryVal(new NodeDefinition("dither", "Dither", "VFX", 178.0f, List.of(NodePort.input("amount", "amount", UniformType.FLOAT, "0.02")), List.of(NodePort.output("value", "value", UniformType.FLOAT)), (nuuUuvvuVV, queueVal, string) -> "((wild_hash12(gl_FragCoord.xy) - 0.5) * " + nuuUuvvuVV.primaryVal(queueVal, "amount") + ")"));
    }
}

